use_frameworks!
platform :ios, '13.0'

target 'SpotImAdsSample' do
 pod 'SpotImStandaloneAds', '1.0.6'

  # uncomment the following if you are using RxSwift (iOS < 13.0)
  #pod 'RxSwift'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'NimbusSDK'
        # fixes undefined behavior for NimbusSDK
        # e.g: NimbusGAMLinearPriceMapping.banner().granularities.count gives a random big number
        # NimbusSDK is shipped as sources so it must be compiled with the distribution flag
        # Otherwise, SpotimStandaloneAds, which is a static library, will not be able to reference it correctly.
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end

      # uncomment the following if you are using RxSwift (iOS < 13.0)
#      if target.name == 'RxSwift'
#        # fixes: "Undefined symbols", "Symbol not found" errors for RxSwift
#        # https://github.com/CocoaPods/CocoaPods/issues/9775
#        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
#      end
    end
  end
end
